repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        name: isort
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: ^piso/test_data*
  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.3
    hooks:
    -   id: flake8