repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        name: isort
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        exclude: ^piso/test_data*
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8