name: pre-commit

on:
  - push
  - pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-pre-commit
      cancel-in-progress: ${{github.event_name == 'pull_request'}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
